[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-daisy"
version = "0.1.7"
description = "A modern Django dashboard built with DaisyUI"
authors = [
    { name="Hossein Yaghoubi", email="hossein.yaghoubi13@gmail.com" }
]
license = { text = "Apache-2.0" }
dependencies = [
    "Django>=3.4",
]
keywords = ["django", "admin", "dashboard", "daisyui", "tailwindcss"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

[project.dynamic]
readme = ["readme"]
classifiers = ["classifiers"]

[tool.setuptools]
package-dir = {"" = "django_daisy"}

[tool.setuptools.packages.find]
where = ["django_daisy"]
