name: Test Compatibility on Tag Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11, 3.12]
        django-version: ['3.2', '4.0', '4.1', '5.0']
        exclude:
          - python-version: 3.8
            django-version: '3.2'
          - python-version: 3.9
            django-version: '3.2'
          - python-version: 3.11
            django-version: '3.2'
          - python-version: 3.12
            django-version: '3.2'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install tox tox-gh-actions
          pip install django==${{ matrix.django-version }}

      - name: Run Tests
        run: |
          tox
